plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "D:\\ASP.NET\\ANGULAR_WEBAPI\\ANGULAR\\PortFolio\\Portfolio\\Portfolio\\src"
publishOrigin = "default"
commandOrigin = "heuristics"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]